#!/bin/bash

while getopts "hn:t:c:s:d:" flag ; do
        case $flag in
                h) HELP=1 ;;
                n) NAME=$OPTARG ;;
                t) TARGET=$OPTARG ;;
                c) CONFIGURATION=$OPTARG ;;
                s) SDK=$OPTARG ;;
                d) DISTDIR=$OPTARG ;;
        esac
done

NAME=${NAME:=`git describe --always --long | sed s/^v//`}
TARGET=${TARGET:=`xcodebuild -list | sed -n '/Targets/,/Build/p' | grep '(Active)' | sed 's/(Active)//;s/^ *//;s/ *$//'`}
CONFIGURATION=${CONFIGURATION:=`xcodebuild -list | sed -n '/Configuration/,$p' | grep '(Active)' | sed 's/(Active)//;s/^ *//;s/ *$//'`}
SDK=${SDK:="`xcodebuild -showsdks | grep 'sdk iphoneos' | sed 's/.*-sdk //' | sort | tail -n 1`"}
DISTDIR=${DISTDIR:=~/Releases}

if [[ "$HELP" != "" ]] ; then
        echo "$0 [options]"
        echo " -h               Show help"
        echo " -n <name>        Set distribution name           ($NAME)"
        echo " -t <target>      Set build target                ($TARGET)"
        echo " -c <conf>        Set build configuration         ($CONFIGURATION)"
        echo " -s <sdk>         Set build SDK                   ($SDK)"
        echo " -d <distdir>     Set destination directory       ($DISTDIR)"
        exit -1
fi

echo Creating distribution package named \"$NAME\"
echo " -target $TARGET"
echo " -configuration $CONFIGURATION"
echo " -sdk $SDK"
echo

BD=build/$CONFIGURATION-iphoneos
rm -rf $BD build/$TARGET.build ipa
[ -d $DISTDIR ] || mkdir $DISTDIR
if ( xcodebuild -target "$TARGET" -configuration "$CONFIGURATION" -sdk "$SDK" \
	| egrep --line-buffered '^[^ ]' \
	| sed -l 's| .*/| |' ) ; then
        echo
	echo Packaging...
	mkdir -p ipa/Payload
	mv "$BD/$TARGET.app" ipa/Payload
	PF="${TARGET}_${CONFIGURATION}.mobileprovision"
	[ -f "$PF" ] && echo Using custom provisioning profile. && cp $PF "ipa/Payload/$TARGET.app/embedded.mobileprovision"
	ditto -c -k -X ipa "$BD/$TARGET.ipa"
	rm -rf "build/$CONFIGURATION-iphoneos/Tests.*"
	rm -rf ipa

	DESTINATION="$DISTDIR/$TARGET-$NAME-$CONFIGURATION"
	rm -rf "$DESTINATION"
	mv "build/$CONFIGURATION-iphoneos" "$DESTINATION"
	echo OK. Distribution is in $DESTINATION.
else
	echo failed
	exit -1
fi
