#!/bin/zsh

DIR=$1
YEAR=$(date +%Y)
NAME="Jakob Borg"

mkdir -p $DIR

cat > $DIR/LICENSE <<EOT
Copyright (C) $YEAR $NAME

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

- The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOT

LINE="====================================="

cat > $DIR/README.md <<EOT
$DIR
$LINE[0,${#DIR}]

License
-------

MIT
EOT

cat > $DIR/.gitignore <<EOT
.*.swp
EOT

cd $DIR && (
	git init
	git add -A
	git commit -m "Initial"
	git remote add github git@github.com:calmh/$DIR
	git remote add zlogin zlogin:/srv/git/$DIR.git
)
